# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  schedule:
#    定时执行 16:10 UTC
    - cron: '10 9 * * 0-6'
  push:
    branches: [ master ]
#   pull_request:
#     branches: [ master ]
#  issue_comment:
#    types: [created, deleted]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew jar
    - name: Run jar file
      run: java -jar build/libs/AutoResource-1.0-SNAPSHOT.jar oss-cn-shanghai.aliyuncs.com ${{ secrets.OSS_KEY }} ${{ secrets.OSS_SECRET }} monster-image-backup auto_image_store Bing
    - name: Commit files
      run: |
        git config --local user.email "jiangjiwei0322@outlook.com"
        git config --local user.name "jiangjiwei"
        git add BingImage.json
        git commit -m "update image store"
        git add BingImage.md
        git commit -m "update image md file"
#        git config pull.rebase true
#        git pull
    - name: Push changes
      uses:  ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_GIT_TOKEN }}
        branch: master
