# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  issue_comment:
    types: [created, deleted]
  schedule:
#    定时执行 17:00 UTC
    - cron: '40 7 * * 0-6'
  push:
   branches: [ master ]
#   pull_request:
#     branches: [ master ]

env:
  ENDPOINT: ${{ secrets.END_POINT }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew jar
    - name: Run jar file
      run: |
        echo "this is job1"
        echo "$ENDPOINT"
        java -jar build/libs/AutoResource-1.0-SNAPSHOT.jar oss-cn-shanghai.aliyuncs.com ${{ secrets.OSS_KEY }} ${{ secrets.OSS_SECRET }} monster-image-backup auto_image_store Bing
    - name: Commit files
      run: |
        git config --local user.email "jiangjiwei0322@outlook.com"
        git config --local user.name "jiangjiwei"
        git add BingImage.json
        git commit -m "update image store"
    - name: Push Change
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{secrets.GIT_TOKEN}}
        branch: main
